name: Build firmware
permissions:
  contents: write

on:
  push:
  pull_request:
  workflow_dispatch: 

jobs:
  build:
    runs-on: buildjet-16vcpu-ubuntu-2204
    name: Build
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up build dependencies
        run: |
          sudo apt-get update &&
          sudo apt-get install -y --no-install-recommends \
            build-essential autoconf autotools-dev \
            device-tree-compiler \
            gperf g++-multilib gcc-multilib \
            libnl-3-dev libdbus-1-dev libelf-dev libmpc-dev dwarves
      - name: Get build version
        run: |
          export BUILD_VERSION=$(cat VERSION)
          export BUILD_VERSION_SOURCE="file"
          # For non-main branches, append branch name and timestamp
          if [ "$GITHUB_REF" != "refs/heads/main" ]; then
            export BUILD_VERSION="$BUILD_VERSION-$(echo $GITHUB_REF | sed 's/refs\/heads\///' | sed 's/\//-/')$(date +%Y%m%d%H%M)"
            export BUILD_VERSION_SOURCE="branch"
          fi

          echo "BUILD_VERSION=$BUILD_VERSION" >> $GITHUB_ENV
          echo "BUILD_VERSION_SOURCE=$BUILD_VERSION_SOURCE" >> $GITHUB_ENV
          echo "$BUILD_VERSION" > VERSION
      - name: Build
        run: |
          echo "Version: $BUILD_VERSION (from $BUILD_VERSION_SOURCE)"

          ./update_app.sh
          ./build.sh lunch BoardConfig_IPC/BoardConfig-EMMC-NONE-RV1106_JETKVM_V2.mk
          ./build.sh
      - name: Upload OTA image
        uses: actions/upload-artifact@v4
        with:
          name: OTA Image
          path: output/image/update_ota.tar
          retention-days: 7
      - name: Upload Full image
        uses: actions/upload-artifact@v4
        with:
          name: Full Image
          path: output/image/update.img
          retention-days: 7
      - name: Create compressed buildkit
        run: |
          ./make_buildkit.sh
      - name: Upload buildkit
        uses: actions/upload-artifact@v4
        with:
          name: jetkvm-native-buildkit
          path: buildkit.tar.zst
          retention-days: 7
          compression-level: 0
